module.exports = {
  extends: [
    'angular'
  ],
  rules: {
    'angular/no-service-method': 0,
    "angular/window-service": 0,
    "no-console": 0,
    "angular/log": 0,
    "angular/controller-name": 0,
    "angular/typecheck-string": 0,
    "angular/angularelement": 0,
    "angular/typecheck-object": 0,
    "angular/timeout-service": 0,
    "angular/json-functions": 0,
    "angular/definedundefined": 0,
    "angular/typecheck-number": 0,
    "angular/typecheck-array": 0,
    "angular/typecheck-function": 0,
    "angular/document-service": 0,
    "no-alert": 0,
    "max-params": 0,
    "no-div-regex": 0,
    "prefer-const": 0,
    "max-nested-callbacks": 0,
    "camelcase": 0,
    "no-negated-condition": 0,
    "dot-notation": 0,
    "space-before-function-paren": ["error", "always"],
    "arrow-parens": ["error", "always"],
    "linebreak-style": 0,
    "keyword-spacing": 0,
    "no-unused-vars": 1,
    "object-shorthand": ["error", "properties"],
    "radix": 0,
    "quote-props": 0,
    "no-lonely-if": 0,
    "no-prototype-builtins": 0,
    "no-useless-constructor": 0,
    "no-mixed-operators": 0,
    "default-case": 0,
    "new-cap": 0,
    "max-depth": 1,
    "no-duplicate-imports": 1
  },
  globals: {
    lodash: false,
    _: false,
    angular: false,
    URI: false
  }
}
